### ISSUE TITLE
Handling tests using javascript during headless testing

### ISSUE THREAD

**Issue by timstone** [DEFRA/quke#27]
**v0.1.0**

Currently default driver is set to poltergeist, if there is a test that requires javascript to execute then the test will fail when the test is run.

There either needs to be a way to run any javascript dependant tests using another driver or tagging the test not to run during headless testing.

**Comment by Cruikshanks** [comment]
@timstone Now we have https://github.com/EnvironmentAgency/flood-risk-acceptance-tests , it includes a test that requires javascript to be running (the delete partner confirmation alert window) and for me this works when I'm driving Chrome, Firefox, and PhantomJS.

It might just have been more about the step itself. So when I researched how to do this the docs pointed to needing to do this in your test

```ruby
# Capybara now has built in support for accepting dialog boxes (without
# needing to extra driver specific code or explicit waits). Simply wrap the
# code which causes the dialog with page.accept_confirm. In essence you are
# passing the code which causes the dialog to appear as a block to the method.
# http://www.rubydoc.info/github/jnicklas/capybara/Capybara%2FSession%3Aaccept_confirm
# http://stackoverflow.com/a/26348968/6117745
page.accept_confirm do
  @app.partnership_details_page.remove_link(name).click
end
```

Are you happy for me to close this issue?
